name: Build Flet APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet qrcode Pillow

      - name: Accept Android Licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Build APK
        run: |
          flet build apk --org ru.rt --project gate --product "RTK_Gate"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rtk-app-apk
          path: build/apk/*.apk
          if-no-files-found: error
